name: CI/CD for Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Databricks CLI
        run: |
          mkdir -p ~/.databrickscfg
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host = ${DATABRICKS_HOST}" >> ~/.databrickscfg
          echo "token = ${DATABRICKS_TOKEN}" >> ~/.databrickscfg
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Deploy Notebook to Databricks
        run: python ci_cd/deploy_notebook.py
