name: Deploy Databricks Notebook

on:
  push:
    branches:
      - main  # Trigger this action on a push to the 'main' branch (adjust as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can change the OS as per your requirements

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Use the Python version you require

    - name: Install dependencies
      run: |
        pip install databricks-cli  # Ensure the Databricks CLI is installed

    - name: Set up Databricks credentials
      run: |
        mkdir -p ~/.databrickscfg
        echo "[DEFAULT]" > ~/.databrickscfg
        echo "host = ${DATABRICKS_HOST}" >> ~/.databrickscfg
        echo "token = ${DATABRICKS_TOKEN}" >> ~/.databrickscfg

    - name: Deploy Notebook to Databricks
      run: |
        python ci_cd/deploy_notebook.py
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}  # Store your Databricks host URL in GitHub Secrets
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}  # Store your Databricks token in GitHub Secrets
