name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Vault CLI
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install vault -y

    - name: Login to Vault
      env:
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      run: |
        export VAULT_ADDR=http://127.0.0.1:8200
        echo "${{ secrets.VAULT_TOKEN }}" | vault login -

    - name: Deploy Notebooks
      env:
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      run: python ci_cd/deploy_notebook.py
