name: Deploy Databricks Notebook

on:
  push:
    branches:
      - main  # Trigger this action on a push to the 'main' branch (adjust as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can change the OS as per your requirements

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Use the Python version you require

    - name: Install dependencies
      run: |
        pip install databricks-cli  # Ensure the Databricks CLI is installed

    - name: Set up Databricks CLI configuration
      run: |
        mkdir -p ~/.databrickscfg  # Create the config directory
        echo "[DEFAULT]" > ~/.databrickscfg/databrickscfg  # Create config file
        echo "host = ${DATABRICKS_HOST}" >> ~/.databrickscfg/databrickscfg  # Set host URL
        echo "token = ${DATABRICKS_TOKEN}" >> ~/.databrickscfg/databrickscfg  # Set token

    - name: Deploy Notebook to Databricks
      run: |
        python ci_cd/deploy_notebook.py
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}  # GitHub secret for host URL
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}  # GitHub secret for token
