# .github/workflows/ci_cd.yml

name: CI/CD Pipeline for Databricks Notebook

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code from the repo

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify Python version you require

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install Python dependencies

    - name: Run tests
      run: |
        python ci_cd/run_tests.py  # Run the tests script (can be expanded)

    - name: Set up Databricks CLI
      run: |
        mkdir -p ~/.databrickscfg  # Create the configuration directory
        echo "[DEFAULT]" > ~/.databrickscfg/databrickscfg  # Create config file
        echo "host = ${DATABRICKS_HOST}" >> ~/.databrickscfg/databrickscfg  # Set host URL
        echo "token = ${DATABRICKS_TOKEN}" >> ~/.databrickscfg/databrickscfg  # Set token

    - name: Deploy Notebook to Databricks
      run: |
        python ci_cd/deploy_notebook.py  # Deploy the notebook using the deploy script
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}  # Databricks host URL stored in GitHub secrets
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}  # Databricks token stored in GitHub secrets
